import { fileSymbols } from './file-symbols';
import type { NativeSymbol } from './native-symbol';
import { statusSymbols } from './status-symbols';

export const iconSymbols = {
  ...fileSymbols,
  ...statusSymbols,
  activity: { sf: 'waveform.path.ecg', material: 'monitor_heart' },
  add: { sf: 'plus', material: 'add' },
  agent: { sf: 'teddybear', sfFilled: 'teddybear.fill', material: 'smart_toy' },
  'all-issues': { sf: 'square.stack.3d.up', material: 'stacks' },
  'app-window': { sf: 'macwindow', material: 'web_asset' },
  appearance: { sf: 'circle.lefthalf.filled', material: 'contrast' },
  archive: { sf: 'tray.and.arrow.down', material: 'archive' },
  'arrow-down': { sf: 'arrow.down', material: 'arrow_downward' },
  'arrow-right': { sf: 'arrow.right', material: 'arrow_forward' },
  'arrow-up': { sf: 'arrow.up', material: 'arrow_upward' },
  atlas: {
    sf: 'point.3.connected.trianglepath.dotted',
    sfFilled: 'point.3.filled.connected.trianglepath.dotted',
    material: 'share',
  },
  attach: { sf: 'paperclip', material: 'attach_file' },
  bold: { sf: 'bold', material: 'format_bold' },
  branch: { sf: 'arrow.triangle.branch', material: 'alt_route' },
  camera: { sf: 'camera', material: 'photo_camera' },
  check: { sf: 'checkmark', material: 'check' },
  checklist: { sf: 'checklist', material: 'checklist' },
  'chevron-down': { sf: 'chevron.down', material: 'expand_more' },
  'chevron-left': { sf: 'chevron.left', material: 'chevron_left' },
  'chevron-right': { sf: 'chevron.right', material: 'chevron_right' },
  'chevron-up': { sf: 'chevron.up', material: 'expand_less' },
  'chevron-up-down': { sf: 'chevron.up.chevron.down', material: 'unfold_more' },
  clear: { sf: 'xmark.circle.fill', material: 'cancel' },
  close: { sf: 'xmark', material: 'close' },
  code: { sf: 'chevron.left.forwardslash.chevron.right', material: 'code' },
  'code-map': { sf: 'cube', material: 'deployed_code' },
  collapse: {
    sf: 'arrow.down.right.and.arrow.up.left',
    material: 'close_fullscreen',
  },
  compaction: {
    sf: 'arrow.down.and.line.horizontal.and.arrow.up',
    material: 'vertical_align_center',
  },
  computer: { sf: 'desktopcomputer', material: 'desktop_mac' },
  connection: { sf: 'wifi', material: 'wifi' },
  copy: { sf: 'doc.on.doc', material: 'content_copy' },
  cycle: { sf: 'calendar.badge.clock', material: 'event_repeat' },
  delete: { sf: 'trash', material: 'delete' },
  diagram: { sf: 'flowchart', material: 'schema' },
  diff: { sf: 'plusminus', material: 'difference' },
  domains: { sf: 'circles.hexagongrid', material: 'workspaces' },
  edit: { sf: 'pencil', material: 'edit' },
  engine: { sf: 'gearshape.2', material: 'manufacturing' },
  expand: {
    sf: 'arrow.up.left.and.arrow.down.right',
    material: 'open_in_full',
  },
  explore: { sf: 'safari', material: 'explore' },
  'external-link': { sf: 'arrow.up.right.square', material: 'open_in_new' },
  'fast-mode': { sf: 'bolt', sfFilled: 'bolt.fill', material: 'bolt' },
  filters: { sf: 'slider.horizontal.3', material: 'tune' },
  fit: { sf: 'viewfinder', material: 'fit_screen' },
  flag: { sf: 'flag', material: 'flag' },
  'flat-view': { sf: 'list.bullet', material: 'view_list' },
  goal: { sf: 'target', material: 'target' },
  guide: { sf: 'text.book.closed', material: 'import_contacts' },
  improve: { sf: 'lightbulb', material: 'lightbulb' },
  issue: {
    sf: 'ticket',
    sfFilled: 'ticket.fill',
    material: 'confirmation_number',
  },
  italic: { sf: 'italic', material: 'format_italic' },
  key: { sf: 'key', material: 'key_vertical' },
  maps: {
    sf: 'point.topleft.down.curvedto.point.bottomright.up',
    material: 'route',
  },
  menu: { sf: 'line.3.horizontal', material: 'menu' },
  message: { sf: 'bubble.left', material: 'chat_bubble' },
  milestone: { sf: 'diamond', material: 'diamond' },
  mode: { sf: 'switch.2', material: 'toggle_on' },
  more: { sf: 'ellipsis', material: 'more_horiz' },
  'new-session': { sf: 'square.and.pencil', material: 'edit_square' },
  notifications: { sf: 'bell', material: 'notifications' },
  pair: { sf: 'qrcode', material: 'qr_code' },
  phone: { sf: 'iphone', material: 'smartphone' },
  photos: { sf: 'photo.on.rectangle', material: 'photo_library' },
  'plan-mode': { sf: 'map', material: 'map' },
  plug: { sf: 'powerplug', material: 'power' },
  private: { sf: 'lock', material: 'lock' },
  'pull-request': { sf: 'arrow.triangle.pull', material: 'fork_left' },
  read: { sf: 'book', material: 'menu_book' },
  rename: { sf: 'character.cursor.ibeam', material: 'edit_note' },
  reorder: { sf: 'arrow.up.arrow.down', material: 'drag_indicator' },
  reply: { sf: 'arrowshape.turn.up.left', material: 'reply' },
  resource: { sf: 'square.dashed', material: 'select' },
  retry: { sf: 'arrow.clockwise', material: 'refresh' },
  return: { sf: 'return', material: 'keyboard_return' },
  rules: { sf: 'checkmark.shield', material: 'verified_user' },
  scan: { sf: 'qrcode.viewfinder', material: 'qr_code_scanner' },
  screens: { sf: 'display.2', material: 'screen_share' },
  search: { sf: 'magnifyingglass', material: 'search' },
  server: { sf: 'server.rack', material: 'dns' },
  sessions: {
    sf: 'bubble.left.and.bubble.right',
    sfFilled: 'bubble.left.and.bubble.right.fill',
    material: 'forum',
  },
  settings: {
    sf: 'gearshape',
    sfFilled: 'gearshape.fill',
    material: 'settings',
  },
  sidebar: { sf: 'sidebar.left', material: 'dock_to_left' },
  sparkle: { sf: 'sparkles', material: 'auto_awesome' },
  speaker: { sf: 'speaker.wave.2', material: 'volume_up' },
  'speaker-off': { sf: 'speaker.slash', material: 'volume_off' },
  'state-machine': { sf: 'circle.hexagonpath', material: 'hub' },
  steer: { sf: 'arrow.turn.down.right', material: 'subdirectory_arrow_right' },
  'structure-view': { sf: 'square.grid.2x2', material: 'grid_view' },
  terminal: { sf: 'terminal', material: 'terminal' },
  thinking: { sf: 'brain', material: 'neurology' },
  tool: { sf: 'wrench.adjustable', material: 'build' },
  tours: { sf: 'signpost.right', material: 'signpost' },
  trace: { sf: 'figure.walk', material: 'footprint' },
  'tree-view': { sf: 'list.bullet.indent', material: 'account_tree' },
  triage: { sf: 'tray', material: 'inbox' },
  underline: { sf: 'underline', material: 'format_underlined' },
  usage: { sf: 'gauge.medium', material: 'speed' },
  'view-3d': { sf: 'cube.transparent', material: 'view_in_ar' },
  voice: { sf: 'mic', sfFilled: 'mic.fill', material: 'mic' },
  'voice-off': { sf: 'mic.slash', material: 'mic_off' },
  web: { sf: 'globe', material: 'language' },
  'zoom-in': { sf: 'plus.magnifyingglass', material: 'zoom_in' },
  'zoom-out': { sf: 'minus.magnifyingglass', material: 'zoom_out' },
} as const satisfies Record<string, NativeSymbol>;

export type IconName = keyof typeof iconSymbols;

function isIconName(name: string): name is IconName {
  return Object.hasOwn(iconSymbols, name);
}

export const iconNames: readonly IconName[] =
  Object.keys(iconSymbols).filter(isIconName);
