import { hasFields, isRecord, isString } from '../src/payload-shape.ts';
import type { ServerNotification } from './protocol.gen';
export type UnmappedNotification<Handled extends PropertyKey> = Pick<
  Exclude<ServerNotification, { method: Handled }>,
  'method'
> & { params: Record<string, unknown> };
const protocolMethods = [
  'error',
  'thread/started',
  'thread/status/changed',
  'thread/archived',
  'thread/deleted',
  'thread/unarchived',
  'thread/closed',
  'thread/reverted',
  'skills/changed',
  'thread/name/updated',
  'thread/attachment/updated',
  'thread/goal/updated',
  'thread/goal/cleared',
  'thread/queue/changed',
  'project/changed',
  'thread/project/updated',
  'thread/environment/connected',
  'thread/environment/disconnected',
  'thread/settings/updated',
  'thread/tokenUsage/updated',
  'turn/started',
  'hook/started',
  'turn/completed',
  'hook/completed',
  'turn/diff/updated',
  'turn/plan/updated',
  'item/started',
  'item/autoApprovalReview/started',
  'item/autoApprovalReview/completed',
  'autoApprovalReview/strictReviewRequired',
  'item/completed',
  'rawResponseItem/completed',
  'rawResponse/completed',
  'item/agentMessage/delta',
  'item/plan/delta',
  'command/exec/outputDelta',
  'process/outputDelta',
  'process/exited',
  'item/commandExecution/outputDelta',
  'item/commandExecution/terminalInteraction',
  'item/fileChange/outputDelta',
  'item/fileChange/patchUpdated',
  'serverRequest/resolved',
  'item/mcpToolCall/progress',
  'mcpServer/oauthLogin/completed',
  'mcpServer/startupStatus/updated',
  'mcpServer/event/stream/notification',
  'account/updated',
  'account/gatewayOAuth/changed',
  'account/rateLimits/updated',
  'app/list/updated',
  'remoteControl/status/changed',
  'externalAgentConfig/import/progress',
  'externalAgentConfig/import/completed',
  'fs/changed',
  'item/reasoning/summaryTextDelta',
  'item/reasoning/summaryPartAdded',
  'item/reasoning/textDelta',
  'thread/compacted',
  'model/rerouted',
  'model/verification',
  'modelProvider/authRecoveryStarted',
  'modelProvider/authRecoveryCompleted',
  'turn/moderationMetadata',
  'model/safetyBuffering/updated',
  'warning',
  'guardianWarning',
  'deprecationNotice',
  'configWarning',
  'fuzzyFileSearch/sessionUpdated',
  'fuzzyFileSearch/sessionCompleted',
  'thread/realtime/started',
  'thread/realtime/itemAdded',
  'thread/realtime/item/started',
  'thread/realtime/item/transcript/delta',
  'thread/realtime/item/completed',
  'thread/realtime/transcript/delta',
  'thread/realtime/transcript/done',
  'thread/realtime/outputAudio/delta',
  'thread/realtime/sdp',
  'thread/realtime/error',
  'thread/realtime/closed',
  'windows/worldWritableWarning',
  'windowsSandbox/setupCompleted',
  'account/login/completed',
] satisfies ServerNotification['method'][];
export function isIgnoredNotification<Handled extends Record<string, unknown>>(
  value: unknown,
  handled: Handled,
): value is UnmappedNotification<keyof Handled> {
  if (!isRecord(value)) return false;
  if (!hasFields(value, { method: isString, params: isRecord })) return false;
  return isIgnoredMethod(String(value.method), handled);
}
function isIgnoredMethod(
  method: string,
  handled: Record<string, unknown>,
): boolean {
  return (
    !Object.hasOwn(handled, method) &&
    protocolMethods.some((known): boolean => known === method)
  );
}
