import {
  FeedSubscribeOutput,
  SessionSnapshot,
  SessionUpdate,
} from '@repo/contracts';
import { z } from 'zod';
import recordings from './feed-recordings.json';

export const FeedMock = z.strictObject({
  agent: z.string(),
  recording: z.string(),
  rows: z.array(SessionUpdate),
  stream: z.array(FeedSubscribeOutput),
  snapshot: SessionSnapshot,
});
export type FeedMock = z.infer<typeof FeedMock>;

// Generated by tools/generate-feed-mocks.mts from both Agents' real converters.
export const recordedFeedMocks = z.array(FeedMock).parse(recordings);
